/* 
 * State / marine area code
 * */
export const StateAreaCodes = {
    'AL': 'AL',
    'AK': 'AK',
    'AS': 'AS',
    'AR': 'AR',
    'AZ': 'AZ',
    'CA': 'CA',
    'CO': 'CO',
    'CT': 'CT',
    'DE': 'DE',
    'DC': 'DC',
    'FL': 'FL',
    'GA': 'GA',
    'GU': 'GU',
    'HI': 'HI',
    'ID': 'ID',
    'IL': 'IL',
    'IN': 'IN',
    'IA': 'IA',
    'KS': 'KS',
    'KY': 'KY',
    'LA': 'LA',
    'ME': 'ME',
    'MD': 'MD',
    'MA': 'MA',
    'MI': 'MI',
    'MN': 'MN',
    'MS': 'MS',
    'MO': 'MO',
    'MT': 'MT',
    'NE': 'NE',
    'NV': 'NV',
    'NH': 'NH',
    'NJ': 'NJ',
    'NM': 'NM',
    'NY': 'NY',
    'NC': 'NC',
    'ND': 'ND',
    'OH': 'OH',
    'OK': 'OK',
    'OR': 'OR',
    'PA': 'PA',
    'PR': 'PR',
    'RI': 'RI',
    'SC': 'SC',
    'SD': 'SD',
    'TN': 'TN',
    'TX': 'TX',
    'UT': 'UT',
    'VT': 'VT',
    'VI': 'VI',
    'VA': 'VA',
    'WA': 'WA',
    'WV': 'WV',
    'WI': 'WI',
    'WY': 'WY'
};

export const MarineAreaCodes = {
    'PZ': 'PZ',
    'PK': 'PK',
    'PH': 'PH',
    'PS': 'PS',
    'PM': 'PM',
    'AN': 'AN',
    'AM': 'AM',
    'GM': 'GM',
    'LS': 'LS',
    'LM': 'LM',
    'LH': 'LH',
    'LC': 'LC',
    'LE': 'LE',
    'LO': 'LO'
};

export const RegionCodes = {
    'AL': 'AL',
    'AT': 'AT',
    'GL': 'GL',
    'GM': 'GM',
    'PA': 'PA',
    'PI': 'PI'
};
